// Bundle src/server.ts → dist/server.js as a single ESM file with all
// dependencies (including @modelcontextprotocol/sdk) inlined, so the
// shipped .dxt has zero install-time work.
import { build } from "esbuild";

await build({
  entryPoints: ["src/server.ts"],
  outfile: "dist/server.js",
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node18",
  minify: false,
  banner: {
    // ajv (transitively via @modelcontextprotocol/sdk) emits code that
    // references `require()` at runtime for code-generated validators.
    // In an ESM bundle `require` is not a global, so validation throws
    // ReferenceError on first call (during MCP `initialize`) and the
    // process dies silently. Shim `require` via createRequire to fix.
    js: [
      "#!/usr/bin/env node",
      "// Generated by build.mjs — do not edit.",
      "import { createRequire as __mashiCreateRequire } from 'module';",
      "const require = __mashiCreateRequire(import.meta.url);",
      "",
    ].join("\n"),
  },
});
console.log("✓ dxt/dist/server.js bundled");
