// Bundle src/server.ts → dist/server.js as a single ESM file with all
// dependencies (including @modelcontextprotocol/sdk) inlined, so the
// shipped .dxt has zero install-time work.
import { build } from "esbuild";

await build({
  entryPoints: ["src/server.ts"],
  outfile: "dist/server.js",
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node18",
  minify: false,
  banner: {
    js: "#!/usr/bin/env node\n// Generated by build.mjs — do not edit.\n",
  },
  // ESM CJS interop quirk: Node sometimes needs createRequire shim
  // injected for transitively required CJS deps. esbuild's banner alone
  // doesn't solve it; the `import { createRequire } from 'module'` trick:
  inject: [],
});
console.log("✓ dxt/dist/server.js bundled");
