import type { Company, S2DItem } from "@/types";

export const MOCK_COMPANIES: Company[] = [
  { id: "c-acuity", name: "Acuity", color_hex: "#3B82F6", status: "active" },
  { id: "c-ledgerline", name: "Ledgerline", color_hex: "#10B981", status: "active" },
  { id: "c-northstar", name: "Northstar", color_hex: "#8B5CF6", status: "active" },
  { id: "c-perigon", name: "Perigon", color_hex: "#F59E0B", status: "active" },
  { id: "c-rampart", name: "Rampart", color_hex: "#EC4899", status: "active" },
  { id: "c-tessera", name: "Tessera", color_hex: "#06B6D4", status: "active" },
];

function companyById(id: string) {
  return MOCK_COMPANIES.find((c) => c.id === id) ?? null;
}

const now = new Date();
const iso = (offsetMinutes = 0) =>
  new Date(now.getTime() + offsetMinutes * 60_000).toISOString();

export const MOCK_S2D_ITEMS: S2DItem[] = [
  {
    id: "s-001",
    title: "Reply to Maya re: Q3 roadmap prioritization",
    description:
      "Maya is asking which two of the six initiatives to defer. Needs a decisive answer with rationale.",
    status: "todo",
    pathway: "drafted_response",
    priority: "high",
    est_minutes: 20,
    energy: "high",
    source_type: "gmail",
    source_label: "Gmail · Maya Chen · 2h ago",
    source_url: "#",
    company_id: "c-acuity",
    company: companyById("c-acuity"),
    created_at: iso(-180),
    updated_at: iso(-180),
  },
  {
    id: "s-002",
    title: "Confirm AWS bill anomaly with Marcus",
    description: "$48k spike on the compute line. Need to know if it's the new RAG pipeline.",
    status: "todo",
    pathway: "quick_reply",
    priority: "urgent",
    est_minutes: 5,
    energy: "low",
    source_type: "slack",
    source_label: "Slack · #ops-ledgerline · 31m ago",
    company_id: "c-ledgerline",
    company: companyById("c-ledgerline"),
    created_at: iso(-31),
    updated_at: iso(-31),
  },
  {
    id: "s-003",
    title: "Pricing-tier rewrite for Northstar self-serve",
    description: "Two clean hours to think — needs the comp matrix open and Alex's draft.",
    status: "todo",
    pathway: "heads_down",
    priority: "high",
    est_minutes: 120,
    energy: "high",
    source_type: "manual",
    source_label: "Created manually",
    company_id: "c-northstar",
    company: companyById("c-northstar"),
    created_at: iso(-1440),
    updated_at: iso(-1440),
  },
  {
    id: "s-004",
    title: "Decide on the Tessera reseller contract terms",
    description:
      "Three options on the table from legal. Net-30 vs. Net-60, exclusivity carve-out, MDF clause.",
    status: "todo",
    pathway: "decision_gate",
    priority: "high",
    est_minutes: 15,
    energy: "medium",
    source_type: "fireflies",
    source_label: "Fireflies · Tessera GTM sync · yesterday",
    company_id: "c-tessera",
    company: companyById("c-tessera"),
    created_at: iso(-720),
    updated_at: iso(-720),
  },
  {
    id: "s-005",
    title: "Frame the Q4 board narrative for Perigon",
    description: "What's the one-line story for ARR shape, churn, and AI gross margin?",
    status: "in_progress",
    pathway: "heads_down",
    priority: "urgent",
    est_minutes: 90,
    energy: "high",
    source_type: "calendar",
    source_label: "Calendar · Board prep block · today 10am",
    company_id: "c-perigon",
    company: companyById("c-perigon"),
    created_at: iso(-2880),
    updated_at: iso(-60),
  },
  {
    id: "s-006",
    title: "Sign off on Rampart hiring panel for staff PM",
    description: "Recruiter sent the slate of 4. Need approval to move all to onsite.",
    status: "in_queue",
    pathway: "watching",
    priority: "medium",
    est_minutes: 10,
    energy: "low",
    source_type: "gmail",
    source_label: "Gmail · Priya (Rampart) · 1d ago",
    company_id: "c-rampart",
    company: companyById("c-rampart"),
    queue_reason: "Awaiting reference check from Priya",
    queue_until: iso(60 * 24 * 2),
    created_at: iso(-2160),
    updated_at: iso(-720),
  },
  {
    id: "s-007",
    title: "Walk through the AI eval harness with Acuity eng",
    description: "Eng wants to standardize on llm-as-judge with golden set checked into the repo.",
    status: "in_queue",
    pathway: "meeting_backed",
    priority: "medium",
    est_minutes: 30,
    energy: "medium",
    source_type: "linear",
    source_label: "Linear · ACU-412 · Eng · this week",
    company_id: "c-acuity",
    company: companyById("c-acuity"),
    queue_reason: "In Thursday 9am Acuity eng sync",
    queue_until: iso(60 * 24 * 3),
    created_at: iso(-4320),
    updated_at: iso(-1440),
  },
  {
    id: "s-008",
    title: "Hand off SSO migration spec to Diego",
    description: "All the requirements are in the doc. Diego owns the rollout from here.",
    status: "in_queue",
    pathway: "delegated",
    priority: "medium",
    est_minutes: 10,
    energy: "low",
    source_type: "manual",
    source_label: "Delegated yesterday",
    company_id: "c-ledgerline",
    company: companyById("c-ledgerline"),
    delegated_to: "Diego R.",
    queue_reason: "Delegated to Diego — check Friday",
    queue_until: iso(60 * 24 * 3),
    created_at: iso(-1440),
    updated_at: iso(-60),
  },
  {
    id: "s-009",
    title: "Triage Northstar churn dashboard data drift",
    description: "Numbers don't match Looker. Find the root cause.",
    status: "backlog",
    pathway: "heads_down",
    priority: "medium",
    est_minutes: 45,
    energy: "medium",
    source_type: "slack",
    source_label: "Slack · DM from Alex · 4h ago",
    company_id: "c-northstar",
    company: companyById("c-northstar"),
    created_at: iso(-240),
    updated_at: iso(-240),
  },
  {
    id: "s-010",
    title: "Reply to investor update questions from Ben",
    description: "Three follow-up Qs after this month's update. Mostly clarifying.",
    status: "backlog",
    pathway: "drafted_response",
    priority: "medium",
    est_minutes: 25,
    energy: "medium",
    source_type: "gmail",
    source_label: "Gmail · Ben S. (Vertex) · 6h ago",
    company_id: null,
    company: null,
    created_at: iso(-360),
    updated_at: iso(-360),
  },
  {
    id: "s-011",
    title: "Confirm DPA changes with Perigon's customer",
    description: "Legal redlined. Need to confirm we can accept their data-retention clause.",
    status: "backlog",
    pathway: "decision_gate",
    priority: "high",
    est_minutes: 15,
    energy: "medium",
    source_type: "gmail",
    source_label: "Gmail · Customer Success · 8h ago",
    company_id: "c-perigon",
    company: companyById("c-perigon"),
    created_at: iso(-480),
    updated_at: iso(-480),
  },
  {
    id: "s-012",
    title: "Closed the loop on Tessera onboarding fix",
    status: "done",
    pathway: "drafted_response",
    priority: "medium",
    est_minutes: 20,
    energy: "medium",
    source_type: "linear",
    source_label: "Linear · TES-204",
    company_id: "c-tessera",
    company: companyById("c-tessera"),
    outcome: "Shipped patch and replied to customer.",
    created_at: iso(-1440),
    updated_at: iso(-30),
    done_at: iso(-30),
  },
  {
    id: "s-013",
    title: "Sent revised offer to staff designer candidate",
    status: "done",
    pathway: "quick_reply",
    priority: "high",
    est_minutes: 10,
    energy: "low",
    source_type: "gmail",
    source_label: "Gmail · Recruiter",
    company_id: "c-rampart",
    company: companyById("c-rampart"),
    outcome: "Offer sent. Awaiting response by EOD Fri.",
    created_at: iso(-2880),
    updated_at: iso(-180),
    done_at: iso(-180),
  },
];
