import type { EnrichedContext } from "@/hooks/use-enriched-context";

/**
 * Render the user's enriched_context (plan + pinned sources + refine
 * thread) as a markdown block appended to the standard Claude prompt
 * pack. Only pinned sources surface — the user has explicitly said
 * "these matter," so we keep the prompt focused.
 *
 * Empty plan + zero pinned sources + empty thread returns "" so the
 * caller can just concatenate without conditionals.
 */
export function renderEnrichedContextBlock(ctx: EnrichedContext | null): string {
  if (!ctx) return "";
  const pinned = ctx.pulled_sources.filter((s) => s.pinned);
  const hasPlan = ctx.plan.length > 0;
  const hasPinned = pinned.length > 0;
  const hasThread = ctx.thread.length > 2; // first user+assistant pair is the initial enrich; skip
  if (!hasPlan && !hasPinned && !hasThread) return "";

  const out: string[] = [];
  out.push("---");
  out.push("");
  out.push("# Mashi-Enriched Context");
  out.push("");
  out.push("(Generated by the Sprint Card v2 Enrich agent. Plan and pinned");
  out.push("sources reflect the user's curated view of what's relevant.)");
  out.push("");

  if (hasPlan) {
    out.push("## Plan");
    out.push("");
    ctx.plan.forEach((step, i) => out.push(`${i + 1}. ${step}`));
    out.push("");
  }

  if (hasPinned) {
    out.push("## Pinned Sources");
    out.push("");
    pinned.forEach((s, i) => {
      out.push(`### [${i + 1}] ${s.kind.toUpperCase()} · ${s.label}`);
      if (s.when) out.push(`When: ${s.when.slice(0, 10)}`);
      if (s.snippet) {
        out.push("");
        out.push(s.snippet.trim());
      }
      out.push("");
    });
  }

  if (hasThread) {
    out.push("## Refine Thread");
    out.push("");
    out.push("(The user's follow-up questions while exploring this item.)");
    out.push("");
    // Skip the first canonical pair (user="Enrich this item: …",
    // assistant=plan summary) — that's already implied by the Plan block.
    ctx.thread.slice(2).forEach((t) => {
      out.push(`**${t.role === "user" ? "User" : "Mashi"}**: ${t.content}`);
      out.push("");
    });
  }

  return out.join("\n");
}
